name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  git-lint-config-file:  # id of input
    description: 'Path to git-lint config file'
    required: true
    default: 'git-lint.yml'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
  env:
    LINTER_WORKSPACE: GITHUB_WORKSPACE  
    LINTER_WORKSPACE_CONFIG_FILE: ${{ inputs.git-lint-config-file }}